apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  employee-db-url: jdbc:postgresql://postgres.dda-app.svc.cluster.local:5432/employee_db
  project-db-url: jdbc:postgresql://postgres.dda-app.svc.cluster.local:5432/project_db
  budget-db-url: jdbc:postgresql://postgres.dda-app.svc.cluster.local:5432/budget_db
  db-user: postgres
  db-password: change-me
  kafka-bootstrap: kafka.dda-app.svc.cluster.local:9092
