resources:
- ../../base

namespace: dda-app

images:
- name: 495013583028.dkr.ecr.us-east-1.amazonaws.com/employee-service
  newName: 495013583028.dkr.ecr.us-east-1.amazonaws.com/employee-service
  newTag: prod-latest
- name: 495013583028.dkr.ecr.us-east-1.amazonaws.com/project-service
  newName: 495013583028.dkr.ecr.us-east-1.amazonaws.com/project-service
  newTag: prod-latest
- name: 495013583028.dkr.ecr.us-east-1.amazonaws.com/budget-service
  newName: 495013583028.dkr.ecr.us-east-1.amazonaws.com/budget-service
  newTag: prod-latest

patches:
- path: patch-env.yaml
- path: patch-ingress-host.yaml
